### ISSUE TITLE
Allow target group deletion with httproute

### ISSUE THREAD

**Issue by 22vibhutigoel** [aws/aws-application-networking-k8s#207] opened 2023-04-10 07:38 UTC
**HTTPRoute** objet in Kubernetes creates service & target group both in Amazon VPC Lattice .

**### Case 1** 

eg : Below file will create service & target group under **vpc-lattice-eks** service network 
```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rates
spec:
  parentRefs:
  - name: vpc-lattice-eks
    sectionName: http
    namespace: default
  rules:
  - backendRefs:
    - name: parking
      kind: Service
      namespace: vpc-lattice-ns
      port: 8090
    matches:
    - path:
        type: PathPrefix
        value: /parking
  - backendRefs:
    - name: review
      kind: Service
      namespace: vpc-lattice-ns
      port: 8090
    matches:
    - path:
        type: PathPrefix
        value: /review
```

But when we delete this HTTPRoute , it will fetch the **Service ID** and delete the service from service network but target groups (review,parking ) still exist on AWS console under Amazon VPC Lattice

**### Case 2** 
Same thing working if we are passing weight under **HTTPRoute** config and under logs , able to see its target group deletion logs  

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: inventory
spec:
  parentRefs:
  - name: vpc-lattice-eks
    sectionName: http
    namespace: default
  rules:
  - backendRefs:
    - name: inventory-ver1
      kind: Service
      namespace: vpc-lattice-ns
      port: 8090
      weight: 50
    - name: inventory-ver2
      kind: Service
      namespace: vpc-lattice-ns
      port: 8090
      weight: 50
```

controller Logs 
```
I0410 07:23:00.060489       1 target_group_synthesizer.go:287] Append stale SDK TG to stale list Name k8s-inventory-ver2-vpc-lattice-ns, ARN tg-015987fdc7ea197af
I0410 07:23:00.060538       1 target_group_synthesizer.go:287] Append stale SDK TG to stale list Name k8s-inventory-ver1-vpc-lattice-ns, ARN tg-08196767b73f76be3
I0410 07:23:00.333370       1 target_group_manager.go:187] TGManager delTGInput >>>> {
  TargetGroupIdentifier: "tg-015987fdc7ea197af"
} delTGResp :{
  Arn: "arn:aws:vpc-lattice:us-west-2:xxxxxxxxxxxx:targetgroup/tg-015987fdc7ea197af",
  Id: "tg-015987fdc7ea197af",
  Status: "DELETE_IN_PROGRESS"
}, err <nil>
I0410 07:23:00.333403       1 target_group_synthesizer.go:306] SynthesizeSDKTargetGroups, deleting stale target group <nil>
I0410 07:23:00.625503       1 target_group_manager.go:187] TGManager delTGInput >>>> {
  TargetGroupIdentifier: "tg-08196767b73f76be3"
} delTGResp :{
  Arn: "arn:aws:vpc-lattice:us-west-2:xxxxxxxxxxxx:targetgroup/tg-08196767b73f76be3",
  Id: "tg-08196767b73f76be3",
  Status: "DELETE_IN_PROGRESS"
}, err <nil>
I0410 07:23:00.625551       1 target_group_synthesizer.go:306] SynthesizeSDKTargetGroups, deleting stale target group <nil>
```

Could you please have a look and help here

**Comment by liwenwu-amazon** [comment] 2023-04-10 15:40
This is a duplicate of https://github.com/aws/aws-application-networking-k8s/issues/119.

**Closed** 2023-11-17 17:29 UTC
