### ISSUE TITLE
TG longname bug for service export/imports

### ISSUE THREAD

**Issue by solmonk** [aws/aws-application-networking-k8s#260] opened 2023-05-25 22:22 UTC
If a service is imported and target group is created out of it, the longname for resource becomes invalid.

This may be due to our TG longname format:
```
k8s-{resourcename}-{routename}-{vpcid}
```
For an exported service, HTTP route name is missing.

The root cause is unclear at this point, but we need to figure out why `make e2etest` is failing on `TARGET_GROUP_NAME_LEN_MODE=long`

**Comment by liwenwu-amazon** [comment] 2023-05-26 14:45
Hmmm, this is done by design.    The owner of  serviceexport  only intend to export its k8s service to VPC lattice federation which trigger a controller to create a target group.    The consumer in other VPC needs to use explicit name as service import. 

Controller should `never` trigger creating a target group for serviceimport.

**Comment by solmonk** [comment] 2023-06-01 18:42
I might have root caused this incorrectly but `make e2etest` has been continuously failing if we have longname mode on. Needs further investigation it seems.

**Comment by graehren** [comment] 2023-09-19 22:53
Use case was created to pass conformance testing, but breaks E2E tests. Need to determine how we will handle target group names as part of our work for managedBy Tags and ownership model.

**Comment by graehren** [comment] 2023-09-19 22:54
https://github.com/aws/aws-application-networking-k8s/issues/392

**Comment by mikhail-aws** [comment] 2023-11-08 19:52
should be fixed with #457

**Closed** 2023-11-08 19:52 UTC
Labels: bug, good first issue, needs investigation
