### ISSUE TITLE
Feature request: a way to manage IAM auth policy for a Lattice Service managed by the Controller

### ISSUE THREAD

**Issue by klyubin** [aws/aws-application-networking-k8s#385] opened 2023-09-05 18:35 UTC
Currently, the IAM auth policy of Lattice Services is not managed by the Controller. As a result, if I create a Lattice Service, by creating the relevant K8S resources, the Controller creates a Lattice Service with Auth Type: None. I can then change the Auth Type to IAM auth and provide an IAM auth policy. However, this creates two challenges:
1. This diverges from the declarative way of managing Lattice Services which map to the underlying K8S cluster(s).
2. When the Controller deletes a Service, it deletes its IAM auth policy as well. When it then recreates the service, the IAM auth policy is gone. This means I have to have something running outside of the Controller, that monitors Lattice Services and ensures they have the IAM auth policy I want.

**Comment by solmonk** [comment] 2023-09-05 18:48
This is being tracked in #18 and we are currently aiming for release of auth policy support in v0.1.0 milestone.

**Comment by mikhail-aws** [comment] 2023-09-05 22:16
closing as duplicate of #18

**Closed by mikhail-aws** 2023-09-05 22:16 UTC
